# Generated by the vetiver package; edit with care

Sys.setenv(PINS_CACHE_DIR = "/tmp")

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/opt/ml/my-pins")
v <- vetiver_pin_read(b, "mentalhealthpred")

#* @plumber
function(pr) {
  pr %>%
    pr_filter(
      "logger",
      function(req) {
        # Construct the log message
        log_message <- paste0(
          as.character(Sys.time()),
          " - ",
          req$REQUEST_METHOD,
          " ",
          req$PATH_INFO,
          " - ",
          req$HTTP_USER_AGENT,
          " @ ",
          req$REMOTE_ADDR,
          "\n"
        )
        # 1. Print the log to the console
        cat(log_message)
        # 2. Append the log to a file in the /tmp/ directory
        cat(log_message, file = "/tmp/mentalhealthpred_logs.txt", append = TRUE)
        
        plumber::forward()
      }
    ) %>%
    # Add an endpoint to view the log file
    pr_get("/view-logs", function(res){
      log_file_path <- "/tmp/mentalhealthpred_logs.txt"
      if (file.exists(log_file_path)) {
        # Set the content type to plain text
        res$headers$`Content-Type` <- "text/plain"
        # Return the contents of the file
        readLines(log_file_path)
      } else {
        res$status <- 404
        list(error = "Log file not found. Make a prediction first to generate logs.")
      }
    }) %>%
    # Optional: Add endpoint to clear logs
    pr_delete("/clear-logs", function(res){
      log_file_path <- "/tmp/mentalhealthpred_logs.txt"
      if (file.exists(log_file_path)) {
        file.remove(log_file_path)
        list(message = "Log file cleared successfully")
      } else {
        res$status <- 404
        list(error = "Log file not found")
      }
    }) %>%
    vetiver_api(v)
}